# Generated by Django 4.2 on 2025-03-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keymanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
